# Generated by Django 2.2.1 on 2019-06-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20190529_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='chart',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
