# Generated by Django 2.2.1 on 2019-06-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20190601_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='chart',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='type',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
