# Generated by Django 2.2.1 on 2019-06-03 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_auto_20190601_0818'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveIntegerField(default=0)),
                ('chart', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(default='', max_length=200)),
                ('video_key', models.CharField(max_length=20)),
            ],
        ),
    ]
